# примеры API-запросов

@baseUrl = https://localhost:8000/api

# получение объявлений
GET {{baseUrl}}/advertisements/
Content-Type: application/json

###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token 902ef055a9ac93f18327f1f9c45ab059f1a62c7d

{
  "title": "Шкаф IKEA",
  "description": "Срочно"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/1/
Content-Type: application/json
Authorization: Token 902ef055a9ac93f18327f1f9c45ab059f1a62c7d

{
  "status": "CLOSED"
}

###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=3
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_before=2020-10-01
Content-Type: application/json


POST http://127.0.0.1:8000/api/advertisements/
Authorization: Token c7d5caf860f04733e18701f3feb5ed3aceb4453c
Content-Type: application/json

{
    "title": "Продам велосипед",
    "description": "Хороший велосипед, почти новый. Подходит для города.",
    "status": "OPEN"
}