# Generated by Django 5.2.15 on 2026-07-06 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='measurements/', verbose_name='Изображение'),
        ),
    ]
